export const regionImages: { [key: string]: string } = {
  seoul: '/local-image/Seoul.jpg',
  busan: '/local-image/Busan.jpg',
  incheon: '/local-image/Incheon.jpg',
  daejeon: '/local-image/Daejeon.jpg',
  daegu: '/local-image/Daegu.jpg',
  gwangju: '/local-image/Gwangju.jpg',
  sejong: '/local-image/Sejong.jpg',
  ulsan: '/local-image/Ulsan.jpg',
  jejudo: '/local-image/Jeju.jpg',
  gyeonggido: '/local-image/Gyeonggi.jpg',
  gangwondo: '/local-image/Gangwon.jpg',
  chungcheongbukdo: '/local-image/Chungbuk.jpg',
  chungcheongnamdo: '/local-image/Chungnam.jpg',
  gyeongsangbukdo: '/local-image/Gyeongbuk.jpg',
  gyeongsangnamdo: '/local-image/Gyeongnam.jpg',
  jeollabukdo: '/local-image/Jeonbuk.jpg',
  jeollanamdo: '/local-image/Jeonnam.jpg',
};
